version: '3'
services:
  app:
    container_name: express-graphql-mongodb-boilerplate
    restart: always
    build: .
    ports:
      - '80:8000'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'